'use client';
import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import gsap from 'gsap';
import { Section } from '@/components/section';
import { aiCards, domains, technologies, vStages } from '@/constants/site';
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-80px'},transition:{duration:.7}};
function GlassCard({title,children}:{title:string;children?:React.ReactNode}){return <motion.div {...reveal} className="glass rounded-[2rem] p-6 transition hover:-translate-y-1 hover:border-[#2BA8FF]/45"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/62">{children ?? 'Strategy, architecture, delivery governance, quality evidence, toolchain integration and production-ready handoff.'}</p></motion.div>}
export function VModel(){const [active,setActive]=useState(vStages[0]);useEffect(()=>{gsap.to('.v-node',{scrollTrigger:undefined,stagger:.04,opacity:1,y:0,duration:.6})},[]);return <Section eyebrow="Signature platform" title="Interactive automotive V Model." className="sticky top-0 min-h-screen bg-[#050505]"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[540px] rounded-[2.5rem] border border-white/10 bg-[#111]/60 p-6">{vStages.map((s,i)=>{const left=i<6;const y=8+i%6*17;return <button key={s} onClick={()=>setActive(s)} onMouseEnter={()=>setActive(s)} style={{top:`${y}%`,[left?'left':'right']:`${10+i%3*5}%`}} className={`v-node absolute opacity-0 translate-y-4 rounded-full border px-4 py-3 text-left text-sm backdrop-blur ${active===s?'border-[#2BA8FF] bg-[#2BA8FF]/20 text-white blue-glow':'border-white/15 bg-white/5 text-white/70'}`}>{s}</button>})}<svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100"><path d="M18 10 L50 62 L82 10" fill="none" stroke="rgba(43,168,255,.45)" strokeWidth=".7"/><path d="M50 62 L50 88" stroke="rgba(217,217,217,.3)" strokeWidth=".5"/></svg></div><div className="glass rounded-[2.5rem] p-8"><p className="text-sm uppercase tracking-[.3em] text-[#2BA8FF]">Selected stage</p><h3 className="mt-4 text-4xl font-semibold">{active}</h3>{['Artifacts','Deliverables','Standards','Responsibilities','Tools','Traceability'].map(x=><div key={x} className="mt-5 border-t border-white/10 pt-4"><b>{x}</b><p className="mt-1 text-white/60">ASIL-aware evidence, review records, model/code baselines, verification links and release decisions.</p></div>)}</div></div></Section>}
export function Traceability(){const [node,setNode]=useState('Code');const nodes=['Customer Requirement','Vehicle Requirement','System Requirement','Software Requirement','Code','Unit Test','Integration Test','Vehicle Validation'];return <Section eyebrow="Digital thread" title="Bidirectional traceability from intent to validation."><div className="glass grid gap-4 rounded-[2.5rem] p-8 md:grid-cols-4">{nodes.map((n,i)=><button onClick={()=>setNode(n)} key={n} className={`rounded-2xl p-5 text-left transition ${node===n||Math.abs(nodes.indexOf(node)-i)<=1?'bg-[#2BA8FF]/18 ring-1 ring-[#2BA8FF]/50':'bg-white/[.04]'}`}><span className="text-xs text-white/40">0{i+1}</span><p className="mt-2 font-semibold">{n}</p></button>)}</div></Section>}
export function Marquee(){return <Section eyebrow="Toolchains" title="Technology ecosystems we integrate."><div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.03] py-6"><div className="marquee flex w-max gap-4">{[...technologies,...technologies].map((t,i)=><span key={t+i} className="rounded-full border border-white/10 px-6 py-3 text-white/70">{t}</span>)}</div></div></Section>}
export function HomeSections(){return <><VModel/><Traceability/><Section eyebrow="Solutions" title="Engineering domains for software-defined vehicles." ><div id="solutions" className="grid gap-4 md:grid-cols-3 lg:grid-cols-4">{domains.map(d=><GlassCard key={d} title={d}/>)}</div></Section><Section eyebrow="Execution" title="From customer intent to supported production." ><div className="grid gap-4 md:grid-cols-6">{['Customer','Architecture','Development','Testing','Deployment','Support'].map(x=><GlassCard key={x} title={x}>Gate-driven delivery with measurable readiness and executive visibility.</GlassCard>)}</div></Section><Marquee/><Section eyebrow="AI solutions" title="AI accelerators for engineering intelligence."><div className="grid gap-4 md:grid-cols-3">{aiCards.map(c=><GlassCard key={c} title={c}/>)}</div></Section><Section eyebrow="Talent" title="Specialist staffing without delivery compromise."><div className="grid gap-4 md:grid-cols-3">{['Permanent','Contract','Contract to Hire','Offshore','Dedicated Teams','Global Engineering Talent'].map(c=><GlassCard key={c} title={c}/>)}</div></Section><Section eyebrow="Industries" title="Mobility programs engineered for scale."><div className="grid gap-4 md:grid-cols-3">{['Passenger Vehicles','Electric Vehicles','Commercial Vehicles','ADAS','Autonomous Driving','Software Defined Vehicles'].map(c=><GlassCard key={c} title={c}/>)}</div></Section><Section eyebrow="Why AutoSys" title="Built for production programs."><div className="grid gap-4 md:grid-cols-4">{[['12','V-model stages'],['95+','Lighthouse target'],['24/7','Global delivery'],['100%','Traceable evidence']].map(([n,l])=><div className="glass rounded-[2rem] p-8" key={l}><p className="text-5xl font-semibold text-[#2BA8FF]">{n}</p><p className="mt-2 text-white/60">{l}</p></div>)}</div></Section></>}
